//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class kupnja_goriva
    {
        public int id { get; set; }
        public Nullable<int> putni_nalog_id { get; set; }
        public Nullable<int> mjesto_id { get; set; }
        public decimal cijena { get; set; }
        public decimal kolicina { get; set; }
        public System.DateTime datum { get; set; }
    
        public virtual mjesto mjesto { get; set; }
        public virtual putni_nalog putni_nalog { get; set; }
    }
}
