//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPPK_DATABASEEntities1 : DbContext
    {
        public PPPK_DATABASEEntities1()
            : base("name=PPPK_DATABASEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kupnja_goriva> kupnja_goriva { get; set; }
        public virtual DbSet<mjesto> mjestoes { get; set; }
        public virtual DbSet<putni_nalog> putni_nalog { get; set; }
        public virtual DbSet<ruta> rutas { get; set; }
        public virtual DbSet<servi> servis { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<tip_vozila> tip_vozila { get; set; }
        public virtual DbSet<vozac> vozacs { get; set; }
        public virtual DbSet<vozilo> voziloes { get; set; }
        public virtual DbSet<zauzece_vozac> zauzece_vozac { get; set; }
        public virtual DbSet<zauzece_vozilo> zauzece_vozilo { get; set; }
    }
}
