//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class putni_nalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public putni_nalog()
        {
            this.kupnja_goriva = new HashSet<kupnja_goriva>();
            this.rutas = new HashSet<ruta>();
        }
    
        public int id { get; set; }
        public Nullable<int> vozac_id { get; set; }
        public Nullable<int> vozilo_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public System.DateTime datum_izrade { get; set; }
        public System.DateTime datum_pocetka { get; set; }
        public System.DateTime datum_zavrsetka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kupnja_goriva> kupnja_goriva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ruta> rutas { get; set; }
        public virtual status status { get; set; }
        public virtual vozac vozac { get; set; }
        public virtual vozilo vozilo { get; set; }
    }
}
