//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ruta
    {
        public int id { get; set; }
        public Nullable<int> putni_nalog_id { get; set; }
        public decimal x_koordinata_a { get; set; }
        public decimal y_koordinata_a { get; set; }
        public decimal x_koordinata_b { get; set; }
        public decimal y_koordinata_b { get; set; }
        public decimal km_izmedu_a_b { get; set; }
        public decimal prosjecna_brzina { get; set; }
    
        public virtual putni_nalog putni_nalog { get; set; }
    }
}
