//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class servi
    {
        public int id { get; set; }
        public Nullable<int> vozilo_id { get; set; }
        public System.DateTime datum_servisa { get; set; }
        public string naziv_servisa { get; set; }
        public decimal cijena { get; set; }
        public string info { get; set; }
    
        public virtual vozilo vozilo { get; set; }
    }
}
