//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_Web
{
    using PPPK_Web.CustomValidators;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class vozac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vozac()
        {
            this.putni_nalog = new HashSet<putni_nalog>();
            this.zauzece_vozac = new HashSet<zauzece_vozac>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Ime je obavezno")]
        public string ime { get; set; }
        [Required(ErrorMessage = "Prezime je obavezno")]
        public string prezime { get; set; }
        [Required(ErrorMessage = "Broj mobitela je obavezan")]
        [BrojMobitelaValidator(ErrorMessage = "Neispravan broj mobitela! (Vazeci brojevi su +385922345678,385912345678 ili 0922345678)")]
        public string broj_mobitela { get; set; }
        [Required(ErrorMessage = "Broj vozacke je obavezan")]
        [BrojVozackeValidator(ErrorMessage = "Neispravan broj vozacke! (Vazece vozacke su izmedu 7 i 14 znakova)")]
        public string broj_vozacke { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<putni_nalog> putni_nalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zauzece_vozac> zauzece_vozac { get; set; }
    }
}
