//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kombinacija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kombinacija()
        {
            this.KombinacijaDetaljis = new HashSet<KombinacijaDetalji>();
        }
    
        public int IDKombinacija { get; set; }
        public int BrojObroka { get; set; }
        public System.DateTime DatumKreiranja { get; set; }
        public Nullable<System.DateTime> VrijediDo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KombinacijaDetalji> KombinacijaDetaljis { get; set; }
    }
}
