//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KombinacijaDetalji
    {
        public int IDKombinacijaDetalji { get; set; }
        public Nullable<int> NazivObrokaID { get; set; }
        public int PostotakUgljikohidrata { get; set; }
        public int PostotakMasti { get; set; }
        public int PostotakProteina { get; set; }
        public int PostotakUkupno { get; set; }
        public Nullable<int> KombinacijaID { get; set; }
    
        public virtual Kombinacija Kombinacija { get; set; }
        public virtual NazivObroka NazivObroka { get; set; }
    }
}
