//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Namirnica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Namirnica()
        {
            this.Obroks = new HashSet<Obrok>();
        }
    
        public int IDNamirnica { get; set; }
        public string Naziv { get; set; }
        public string Energija_kcal { get; set; }
        public string Energija_kJ { get; set; }
        public Nullable<int> TipNamirniceID { get; set; }
        public Nullable<int> JedinicaID { get; set; }
        public int Kolicina { get; set; }
    
        public virtual Jedinica Jedinica { get; set; }
        public virtual TipNamirnice TipNamirnice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obrok> Obroks { get; set; }
    }
}
