//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NazivObroka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NazivObroka()
        {
            this.KombinacijaDetaljis = new HashSet<KombinacijaDetalji>();
            this.Obroks = new HashSet<Obrok>();
        }
    
        public int IDNazivObroka { get; set; }
        public string Ime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KombinacijaDetalji> KombinacijaDetaljis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obrok> Obroks { get; set; }
    }
}
